-- Primera entrega del proyecto final 
-- Tiziana Maddalena 
DROP SCHEMA IF EXISTS PRADA ;
CREATE SCHEMA IF NOT EXISTS PRADA ;
USE PRADA;

DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE IF NOT EXISTS CLIENTES (
	ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR (25) NOT NULL,
    APELLIDO VARCHAR (30) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL, 
	PRIMARY KEY (ID_CLIENTE)
);

DROP TABLE IF EXISTS PEDIDOS;
CREATE TABLE IF NOT EXISTS PEDIDOS (
	ID_PEDIDO int NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL, 
    FECHA DATE NOT NULL,
    MONTO DECIMAL(10,2),
	PRIMARY KEY (ID_PEDIDO)
);


DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE IF NOT EXISTS PRODUCTOS (
	ID_PRODUCTO INT NOT NULL,
    NOMBRE VARCHAR (25) NOT NULL,
    DESCRIPCION VARCHAR(50), 
    PRECIO DECIMAL(10,2),
    STOCK INT NOT NULL,
    ID_CATEGORIA INT,
	PRIMARY KEY (ID_PRODUCTO)
);

DROP TABLE IF EXISTS CATEGORIA_PROD;
CREATE TABLE IF NOT EXISTS CATEGORIA_PROD (
	ID_CATEGORIA INT NOT NULL,
    NOMBRE VARCHAR(15) NOT NULL,
	DESCRIPCION VARCHAR(50), 
	PRIMARY KEY (ID_CATEGORIA)
);

DROP TABLE IF EXISTS DISENADORES;
CREATE TABLE IF NOT EXISTS DISENADORES (
	ID_DISENADOR INT NOT NULL,
	NOMBRE VARCHAR (25) NOT NULL,
    APELLIDO VARCHAR (30) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
	PRIMARY KEY (ID_DISENADOR)
);

DROP TABLE IF EXISTS COLECCIONES;
CREATE TABLE IF NOT EXISTS COLECCIONES (
	ID_COLECCION INT NOT NULL,
	NOMBRE VARCHAR (25) NOT NULL,
    DESCRIPCION VARCHAR(150),
    LANZAMIENTO DATE, 
    ID_DISENADOR INT NOT NULL,
	PRIMARY KEY (ID_COLECCION)
);

DROP TABLE IF EXISTS MODELOS;
CREATE TABLE IF NOT EXISTS MODELOS (
	ID_MODELO INT NOT NULL,
	NOMBRE VARCHAR (25) NOT NULL,
    APELLIDO VARCHAR (30) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    PAIS_ORIGEN VARCHAR(15),
    ALTURA INT, 
    PESO INT, 
	PRIMARY KEY (ID_MODELO)
);

DROP TABLE IF EXISTS DESFILES;
CREATE TABLE IF NOT EXISTS DESFILES (
	ID_DESFILE INT NOT NULL,
	NOMBRE VARCHAR (25) NOT NULL,
    DESCRIPCION VARCHAR(150),
    FECHA DATE, 
    CIUDAD VARCHAR(15),
    PAIS VARCHAR(15),
    UBICACION VARCHAR(15),
    ID_MODELO INT NOT NULL, 
    ID_COLECCION INT NOT NULL, 
	PRIMARY KEY (ID_DESFILE)
);


ALTER TABLE PEDIDOS
ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE); 

ALTER TABLE PEDIDOS
ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO); 

ALTER TABLE PRODUCTOS
ADD FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PROD(ID_CATEGORIA); 

ALTER TABLE COLECCIONES 
ADD FOREIGN KEY (ID_DISENADOR) REFERENCES DISENADORES(ID_DISENADOR);

ALTER TABLE DESFILES
ADD FOREIGN KEY (ID_MODELO) REFERENCES MODELOS(ID_MODELO);

ALTER TABLE DESFILES
ADD FOREIGN KEY (ID_COLECCION) REFERENCES COLECCIONES(ID_COLECCION);


